
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-s24-5pm-2
owner: ucsb-cs156-s24
repo_name: proj-organic-s24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"AbhishekCreateCourseP","number":24,"title":"Abhishek - Create Course Show Page (Hyperlinks for Each Individual Course)","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/pull/24"},{"author":{"id":"U_kgDOBdHiDg","is_bot":false,"login":"NevMan1","name":""},"headRefName":"nevin-feat-home-redo","number":23,"title":"Introduction  Website Description","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/pull/23"},{"author":{"id":"U_kgDOBdHiDg","is_bot":false,"login":"NevMan1","name":""},"headRefName":"nevin-feat-home","number":15,"title":"Done with home page","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/pull/15"},{"author":{"id":"U_kgDOBsO-4g","is_bot":false,"login":"richardfang888","name":"Richard Fang"},"headRefName":"Richard--Staff-CRUD","number":10,"title":"Added Form, Form test, and Form story for Staff component","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/pull/10"}]
