
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-s24-5pm-2
owner: ucsb-cs156-s24
repo_name: proj-organic-s24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"AbhishekSwaggerOption","number":13,"title":"Abhishek - This changes the two files that then allow for navbar swagger turn on.","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/pull/13"},{"author":{"id":"U_kgDOBdC-cw","is_bot":false,"login":"nicoshinozaki","name":""},"headRefName":"Nico-SpringBootv3","number":12,"title":"Nico - Updated Backend to Spring Boot 3","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/pull/12"},{"author":{"id":"U_kgDOBsO-4g","is_bot":false,"login":"richardfang888","name":"Richard Fang"},"headRefName":"Richard--Staff-CRUD","number":10,"title":"Added Form, Form test, and Form story for Staff component","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-2/pull/10"}]
